### ISSUE TITLE
Owlbot v1 endpoint is deprecated

### ISSUE THREAD

**Issue by payamnj** [thebhatman/ConnectAll#2]
Please consider using version 2 of the Owlbot API.
you can do so just by changing the `v1` in the endpoint URL to `v2` the only difference between these two versions is that a spelling typo in the response is fixed. Version 1 is deprecated and going to be redirected to the version 2  soon. So if your code expects the key with the wrong spelling `defenition` instead of `definition` it may break after the redirect.
Also, you may want to check version 3 which has the pronunciation
and image for some of the nouns. In version 3,  the JSON structure of the response is different and it requires authentication token in the request header, registering for a token at [OwlBot](https://owlbot.info) is free🦉🤖.

**Comment by thebhatman** [comment]
Thank you @payamnj for bringing this to my notice. I will change the endpoint to version 2.

**Comment by thebhatman** [comment]
Fixed by commit https://github.com/thebhatman/ConnectAll/commit/e770676784dc07cca6336e51a84df8ee4b073480. 
Thanks!

**Comment by payamnj** [comment]
https://github.com/thebhatman/ConnectAll/blob/e770676784dc07cca6336e51a84df8ee4b073480/zulip_bot/python-zulip-api/zulip_bots/zulip_bots/bots/define/define.py#L67
please also change the `defenition` key to `definition` .

**Comment by thebhatman** [comment]
Done. Thank you!
